### ISSUE TITLE
Update to repo-guidelines

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/match_tracker#1]
Can you update this to follow the [repo-guidelines](https://github.com/IBM-Bluemix/repo-guidelines)? It's a great demo and I'd like to get it into the content-microservice

**Comment by jthomas** [comment]
Will do. It's on the backlog for my Trello board for this project. Been busy travelling, hoping to get time to finish this off in a week or so!

**Comment by jthomas** [comment]
I've updated the repo with the following changes to match the repo guidelines:
- Added license header to source code files
- Added License and Notice files.

The README file follows the structure suggested (intro, architecture, deployment, running locally..).

This demo is complex to deploy, due to the database setup and other initialisation tasks needed. I've written scripts to assist the user but it still requires manually steps and therefore isn't suitable for the "Deploy To Bluemix button".

I believe this issue can be closed, thoughts @JakePeyser ?

**Comment by jakepeyser** [comment]
Fixed a small typo in b447bf47d15e5d9aeaec09826e86a1d98e5f5752, otherwise LGTM

**Comment by jthomas** [comment]
That wasn't a typo 😀
Can you revert this?

**Comment by jakepeyser** [comment]
My apologies, I had never seen that `npm` command syntax. Change reverted
